ARG BASEIMAGE
FROM ${BASEIMAGE}

CMD ["/bin/bash"]

# Base packages
RUN dnf update -y \
 && dnf install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r) \
 && dnf clean all \
 && rm -rf /var/cache/yum

# Install CUDA
RUN curl -ksL https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo -o /etc/yum.repos.d/cuda.repo \
 && rpm -i https://developer.download.nvidia.com/compute/machine-learning/repos/rhel8/x86_64/nvidia-machine-learning-repo-rhel8-1.0.0-1.x86_64.rpm \
 && dnf update -y \
 && dnf clean all \
 && rm -rf /var/cache/yum

# Install nVidia drivers
RUN curl -ksL https://us.download.nvidia.com/XFree86/Linux-x86_64/460.56/NVIDIA-Linux-x86_64-460.56.run -o /opt/nvidia-drivers.run \
 && chmod +x /opt/nvidia-drivers.run \
 && /opt/nvidia-drivers.run \
 && rm /opt/nvidia-drivers.run


# Since UE4 refuses to run as the root user under Linux, create a non-root user
RUN useradd --create-home --home /home/ue4 --shell /bin/bash --uid 1000 ue4 && \
	usermod -a -G audio,video ue4
USER ue4
