ARG BASEIMAGE
FROM ${BASEIMAGE}

# Enable Vulkan support
RUN dnf update -y \
 && dnf install -y kernel-devel-$(uname -r) kernel-headers-$(uname -r)

# Since UE4 refuses to run as the root user under Linux, create a non-root user
RUN useradd --create-home --home /home/ue4 --shell /bin/bash --uid 1000 ue4 && \
	usermod -a -G audio,video ue4
USER ue4